# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Pour les projets Node.js
    directory: "/" # Racine du projet
    schedule:
      interval: "always"  # Déclenche lors d'un push
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ton-nom-github"  # Optionnel, assigne quelqu'un
  # Spécifie la branche cible

  - package-ecosystem: "composer" # Pour les projets PHP
    directory: "/"
    schedule:
      interval: "always"  # Déclenche lors d'un push# Spécifie la branche cible
    - package-ecosystem: "" # Pour les projets PHP
    directory: "/"
    schedule:
      interval: "always"  #
