on:
  push:
    branches:
      - "feat/test-brancheeeee"
  pull_request:
    branches:
      - "feat/test-brancheeeee"
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit

updates:
  - package-ecosystem: "npm"  # Pour les projets Node.js
    directory: "/"  # Racine du projet
    schedule:
      interval: "daily"  # Vérifie tous les jours
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ton-nom-github"
    branches:
      - "feat/test-brancheeeee"

  - package-ecosystem: "composer"  # Pour les projets PHP
    directory: "/"
    schedule:
      interval: "daily"
    branches:
      - "feat/test-brancheeeee"
