version: 2
updates:
  - package-ecosystem: "npm" # Pour les projets Node.js
    directory: "/" # Racine du projet
    schedule:
      interval: "always"  # Déclenche lors d'un push
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ton-nom-github"  # Optionnel, assigne quelqu'un

  - package-ecosystem: "composer" # Pour les projets PHP
    directory: "/"
    schedule:
      interval: "always"  # Déclenche lors d'un push
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
